---
- name: Install nginx
  apt: name=nginx state=latest update_cache=yes force=yes
  notify:
    - Start Nginx

# App settings - TODO: select which do you need from config
- name: Install main Nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - Reload Nginx

- name: Install API service Nginx config
  template: src=api.conf.j2 dest=/etc/nginx/sites-enabled/api.conf
  notify:
    - Reload Nginx

- name: Install Auth service Nginx config
  template: src=auth.conf.j2 dest=/etc/nginx/sites-enabled/auth.conf
  notify:
    - Reload Nginx

- name: Install Client service Nginx config
  template: src=client.conf.j2 dest=/etc/nginx/sites-enabled/client.conf
  notify:
    - Reload Nginx
