name: serverus
memory: 512
private_ip: 192.168.50.4
forward_ports:
  - {guest: 80, host: 8000}

digital_ocean:
  toklen: <your digital ocean token>
  image:  Ubuntu 14.04 x32
  region: Amsterdam 1
  size:   512MB # 1GB