---
- hosts: vagrant
  user: vagrant
  sudo: yes
  vars:
    - distro_codename: trusty
    - domain: vagrant
    - home_dir: /home/deployer
    - api_dir: /home/deployer/api/current
    - client_dir: /home/deployer/client
    - auth_dir: /home/deployer/auth/current
    - postgresql_version: "9.3"
    - db_user: deployer
    - db_user_pass: deployer
    - db_user_roles: SUPERUSER
    - db_name: db_development

  roles:
    - common
    - ruby
    - postgres
    - elasticsearch
    - deploy-user
    - nginx
    - unicorn
