---
- hosts: production
  user: root
  sudo: yes
  vars:
    - distro_codename: trusty
    - domain: domain.com
    - home_dir: /home/deployer
    - api_dir: /home/deployer/api/current  # when using mina deploy we need /current
    - client_dir: /home/deployer/client
    - auth_dir: /home/deployer/auth/current
    - postgresql_version: "9.3"
    - db_user: deployer
    - db_user_pass: deployer
    - db_user_roles: SUPERUSER
    - db_name: db_production

  roles:
    - common
    - deploy-user
    - nginx
    - ruby
    - unicorn
    - postgres
