---
- hosts: vagrant
  user: vagrant
  sudo: yes
  # uncomment for faster provisioning
  gather_facts: False
  vars:
    - distro_codename: trusty
    - domain: vagra.nt
    - home_dir: /home/vagrant
    - api_dir: /home/vagrant/api
    - client_dir: /home/vagrant/client
    - auth_dir: /home/vagrant/auth
    - postgresql_version: "9.3"
    - db_user: vagrant
    - db_user_pass: vagrant
    - db_user_roles: SUPERUSER
    - db_name: db_development

  roles:
    - common
    - ruby
    - postgres
    - elasticsearch
    # no need for local setup, uncomment for testing on Vagrant
    # - deploy-user
    # - nginx
    # - unicorn
