- name: Install JRE
  apt: pkg=openjdk-7-jre-headless state=latest install_recommends=no update_cache=yes

- name: Download ElasticSearch package
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.2.deb dest=~/elasticsearch-1.4.2.deb

- name: Install ElasticSearch from .deb file
  shell: dpkg -i ~/elasticsearch-1.4.2.deb
  notify:
    - Restart ElasticSearch
